server:
  port: 8189

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG

management:
  server:
    port: 8199
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

springdoc:
  packagesToScan: uk.gov.justice.laa.crime.evidence
  show-actuator: true
  api-docs:
    path: /crime-evidence
    enabled: true

  swagger-ui:
    path: /open-api/docs.html
    enabled: true
    operationsSorter: method

spring:
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST_PORT}/${DATASOURCE_DBNAME}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 3600000

  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml
    enabled: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
