server:
  port: 8089

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG

management:
  server:
    port: 8099
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

springdoc:
  packagesToScan: uk.gov.justice.laa.crime.evidence
  show-actuator: true
  api-docs:
    path: /crime-evidence
    enabled: true

  swagger-ui:
    path: /open-api/docs.html
    enabled: true
    operationsSorter: method



