server:
  port: 8189

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG

management:
  server:
    port: 8199
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

springdoc:
  packagesToScan: uk.gov.justice.laa.crime.evidence
  show-actuator: true
  api-docs:
    path: /crime-evidence
    enabled: true

  swagger-ui:
    path: /open-api/docs.html
    enabled: true
    operationsSorter: method

spring:
  datasource:
    url: jdbc:postgresql://${DATASOURCE_HOST_PORT}/${DATASOURCE_DBNAME}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 3600000

  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml
    enabled: true

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: false
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false

  security:
    oauth2:
      client:
        provider:
          maat-api:
            token-uri: ${MAAT_API_OAUTH_URL}
        registration:
          maat-api:
            client-id: ${MAAT_API_OAUTH_CLIENT_ID}
            client-secret: ${MAAT_API_OAUTH_CLIENT_SECRET}
            authorization-grant-type: client_credentials
      resource-server:
        jwt:
          issuer-uri: ${crime-evidence.security.issuer-uri}

retry-config:
  max-retries: 3
  min-back-off-period: 5
  jitter-value: 0.75

crime-evidence:
  security:
    issuer-uri: http://localhost:${server.port}

services:
  maat-api:
    oAuthEnabled: true
    baseUrl: ${MAAT_API_BASE_URL}
    assessments-domain: /api/internal/v1/assessment
    rep-order-endpoints:
      reporder-capital-url: ${services.maat-api.assessments-domain}/rep-orders/capital/reporder/{repId}
