version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "8189:8189"
      - "8199:8199"
      - "8091:8091"

    depends_on:
      - postgres

  postgres:
    image: postgres:14.3
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
