--liquibase formatted sql
--changeset muthus:06-income-evidence-required-create

CREATE TABLE IF NOT EXISTS crime_evidence.INCOME_EVIDENCE_REQUIRED
(
    ID INTEGER NOT NULL PRIMARY KEY,
    MCOO_OUTCOME VARCHAR(20) NOT NULL,
    APPLICANT_EMST_CODE VARCHAR(20),
    EVIDENCE_ITEMS_REQUIRED INTEGER NOT NULL,
    ANNUAL_PENSION_AMOUNT INTEGER,
    APPLICANT_PARTNER VARCHAR(10),
    PARTNER_EMST_CODE VARCHAR(20),
    DATE_CREATED TIMESTAMP NOT NULL,
    USER_CREATED VARCHAR(100) NOT NULL,
    DATE_MODIFIED TIMESTAMP,
    USER_MODIFIED VARCHAR(100),
    UNIQUE (MCOO_OUTCOME, APPLICANT_EMST_CODE, ANNUAL_PENSION_AMOUNT, APPLICANT_PARTNER, PARTNER_EMST_CODE)
);